UNLOAD (
  SELECT
    CAST(class AS VARCHAR) AS class,
    CAST(time AS VARCHAR) AS time,
    CAST(v1 AS VARCHAR) AS v1, CAST(v2 AS VARCHAR) AS v2, CAST(v3 AS VARCHAR) AS v3, CAST(v4 AS VARCHAR) AS v4,
    CAST(v5 AS VARCHAR) AS v5, CAST(v6 AS VARCHAR) AS v6, CAST(v7 AS VARCHAR) AS v7, CAST(v8 AS VARCHAR) AS v8,
    CAST(v9 AS VARCHAR) AS v9, CAST(v10 AS VARCHAR) AS v10, CAST(v11 AS VARCHAR) AS v11, CAST(v12 AS VARCHAR) AS v12,
    CAST(v13 AS VARCHAR) AS v13, CAST(v14 AS VARCHAR) AS v14, CAST(v15 AS VARCHAR) AS v15, CAST(v16 AS VARCHAR) AS v16,
    CAST(v17 AS VARCHAR) AS v17, CAST(v18 AS VARCHAR) AS v18, CAST(v19 AS VARCHAR) AS v19, CAST(v20 AS VARCHAR) AS v20,
    CAST(v21 AS VARCHAR) AS v21, CAST(v22 AS VARCHAR) AS v22, CAST(v23 AS VARCHAR) AS v23, CAST(v24 AS VARCHAR) AS v24,
    CAST(v25 AS VARCHAR) AS v25, CAST(v26 AS VARCHAR) AS v26, CAST(v27 AS VARCHAR) AS v27, CAST(v28 AS VARCHAR) AS v28,
    CAST(amount AS VARCHAR) AS amount
  FROM "{DATABASE}"."raw"
  WHERE rand() < 0.8
)
TO '{S3_BUCKET}'
WITH (format='CSV');
